---
- name: Package installation
  hosts: all
  ignore_errors: True
  
  tasks:

  - name: "Stop mariadb service"
    service:
      name: mariadb
      state: stopped
      
  - name: Remove mariadb
    yum:
      name: 
        - "MariaDB-*"
  #      - MariaDB-server
  #      - MariaDB-client
      state: absent
