---
- name: Package installation
  hosts: all
  
  tasks:

  - name: "Stop mariadb service"
    service:
      name: mariadb
      state: stopped
  
  - name: Remove mariadb
    yum:
      name: mariadb-server
      state: absent
