---
- name: Package installation
  hosts: all
  
  tasks:

  - name: "Stop mariadb service"
    service:
      name: mariadb
      state: stopped
    ignore_errors: True
  
  - name: Remove mariadb
    yum:
      name: 
        - MariaDB-server
        - MariaDB-client
      state: absent
