---
- name: Package installation
  hosts: all
  ignore_errors: True
  
  tasks:

  - name: "Stop mariadb service"
    service:
      name: mariadb
      state: stopped
      
  - name: Remove mariadb
    yum:
      state: absent
      name: 
        - MariaDB-server
        - MariaDB-client
